version: '2.2'

services:
  manticore:
    container_name: manticore
    image: manticoresearch/manticore:6.0.4
    environment:
      - EXTRA=1
    restart: always
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
          #    volumes:
          #- ./data:/var/lib/manticore

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: backend.dockerfile
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8090:8000"
    depends_on:
      - manticore

#      - ./manticore.conf:/etc/manticoresearch/manticore.conf # uncomment if you use a custom config
